// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF9Vv1r4HROr-HrFEpDRFAKN9r-mp1i1Q',
    appId: '1:532145120675:web:6ef8deaf9c7c2be26ea616',
    messagingSenderId: '532145120675',
    projectId: 'mango-746b4',
    authDomain: 'mango-746b4.firebaseapp.com',
    storageBucket: 'mango-746b4.firebasestorage.app',
    measurementId: 'G-3EP296GJE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX8DEa6fv3FgKCj5OzHQA6xSpq8blim_w',
    appId: '1:532145120675:android:6aadcb6fb53a5de56ea616',
    messagingSenderId: '532145120675',
    projectId: 'mango-746b4',
    storageBucket: 'mango-746b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9SRnmbya22yX7qSPaP1oRiqcEu1GoYeU',
    appId: '1:532145120675:ios:c5ca9af5ac9fc2c66ea616',
    messagingSenderId: '532145120675',
    projectId: 'mango-746b4',
    storageBucket: 'mango-746b4.firebasestorage.app',
    iosBundleId: 'com.example.belajarFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9SRnmbya22yX7qSPaP1oRiqcEu1GoYeU',
    appId: '1:532145120675:ios:c5ca9af5ac9fc2c66ea616',
    messagingSenderId: '532145120675',
    projectId: 'mango-746b4',
    storageBucket: 'mango-746b4.firebasestorage.app',
    iosBundleId: 'com.example.belajarFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF9Vv1r4HROr-HrFEpDRFAKN9r-mp1i1Q',
    appId: '1:532145120675:web:6e6f2ed44ccdd1866ea616',
    messagingSenderId: '532145120675',
    projectId: 'mango-746b4',
    authDomain: 'mango-746b4.firebaseapp.com',
    storageBucket: 'mango-746b4.firebasestorage.app',
    measurementId: 'G-58SRVV5330',
  );
}
