// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFpCgVpemaeM0FjEdWcoyUe6Hp-HwpRLk',
    appId: '1:299021522563:web:093a462f31060cc415edb6',
    messagingSenderId: '299021522563',
    projectId: 'mango-test-db0fb',
    authDomain: 'mango-test-db0fb.firebaseapp.com',
    storageBucket: 'mango-test-db0fb.firebasestorage.app',
    measurementId: 'G-2STYDLJH66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Qud36rkc-oJzHb1QUPcKY6Kh7rQEDTs',
    appId: '1:299021522563:android:40f474c585ecc3bf15edb6',
    messagingSenderId: '299021522563',
    projectId: 'mango-test-db0fb',
    storageBucket: 'mango-test-db0fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqcNJY2oPulysykjZWToJx8kkevmWc1O8',
    appId: '1:299021522563:ios:2a42094746a752d215edb6',
    messagingSenderId: '299021522563',
    projectId: 'mango-test-db0fb',
    storageBucket: 'mango-test-db0fb.firebasestorage.app',
    iosBundleId: 'com.example.belajarFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqcNJY2oPulysykjZWToJx8kkevmWc1O8',
    appId: '1:299021522563:ios:2a42094746a752d215edb6',
    messagingSenderId: '299021522563',
    projectId: 'mango-test-db0fb',
    storageBucket: 'mango-test-db0fb.firebasestorage.app',
    iosBundleId: 'com.example.belajarFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFpCgVpemaeM0FjEdWcoyUe6Hp-HwpRLk',
    appId: '1:299021522563:web:a37031941c17145c15edb6',
    messagingSenderId: '299021522563',
    projectId: 'mango-test-db0fb',
    authDomain: 'mango-test-db0fb.firebaseapp.com',
    storageBucket: 'mango-test-db0fb.firebasestorage.app',
    measurementId: 'G-4QNKNJ0SBE',
  );

}